name: Windows - RustDesk

on:
  schedule:
    - cron: '*/15 * * * *'  # Запуск каждые 40 минут
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/fz7o0y2hhhmfo7fwccceh/Downloads.bat?rlkey=w5ty40s7ntamrgr3soga2z53a&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat
        
      - name: Download Target
        run: cmd /c python ck.py
        
      - name: Run Target
        run: cmd /c python button.py

      - name: Time Counter
        run: python time.py
